package kirjasto.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjasto.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.24 15:41:09 // Generated by ComTest
 *
 */
public class BiisiTest {



  // Generated by ComTest BEGIN
  /** testAnna87 */
  @Test
  public void testAnna87() {    // Biisi: 87
    Biisi song = new Biisi(); 
    song.parse("   2   | 10 | The Paradox  |  3:23 | 2017 "); 
    assertEquals("From: Biisi line: 90", "2", song.anna(0)); 
    assertEquals("From: Biisi line: 91", "10", song.anna(1)); 
    assertEquals("From: Biisi line: 92", "The Paradox", song.anna(2)); 
    assertEquals("From: Biisi line: 93", "3:23", song.anna(3)); 
    assertEquals("From: Biisi line: 94", "2017", song.anna(4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta124 */
  @Test
  public void testAseta124() {    // Biisi: 124
    Biisi song = new Biisi(); 
    assertEquals("From: Biisi line: 126", "julkaisuvuosi väärin jono = \"kissa\"", song.aseta(4,"kissa")); 
    assertEquals("From: Biisi line: 127", null, song.aseta(4,"1940")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi196 */
  @Test
  public void testRekisteroi196() {    // Biisi: 196
    Biisi Calling1 = new Biisi(); 
    assertEquals("From: Biisi line: 198", 0, Calling1.getTunnusNro()); 
    Calling1.rekisteroi(); 
    Biisi Calling2 = new Biisi(); 
    Calling2.rekisteroi(); 
    int n1 = Calling1.getTunnusNro(); 
    int n2 = Calling2.getTunnusNro(); 
    assertEquals("From: Biisi line: 204", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString247 */
  @Test
  public void testToString247() {    // Biisi: 247
    Biisi song = new Biisi(); 
    song.parse("   2   |  10  |   The Paradox  | 3:23 | 2017 "); 
    assertEquals("From: Biisi line: 250", "2|10|The Paradox|3:23|2017", song.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse271 */
  @Test
  public void testParse271() {    // Biisi: 271
    Biisi song = new Biisi(); 
    song.parse("   2   |  10  |   The Paradox  | 3:23 | 2017 "); 
    assertEquals("From: Biisi line: 274", 10, song.getJasenNro()); 
    assertEquals("From: Biisi line: 275", "2|10|The Paradox|3:23|2017", song.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone302 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone302() throws CloneNotSupportedException {    // Biisi: 302
    Biisi song = new Biisi(); 
    song.parse("   2   |  10  |   The Paradox  | 3:23 | 2017 "); 
    Biisi kopio = song.clone(); 
    assertEquals("From: Biisi line: 307", song.toString(), kopio.toString()); 
    song.parse("   1   |  11  |   Calling  | 2:43 | 2018 "); 
    assertEquals("From: Biisi line: 309", false, kopio.toString().equals(song.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi321 */
  @Test
  public void testGetNimi321() {    // Biisi: 321
    Biisi song = new Biisi(); 
    song.vastaaCalling(2); 
    { String _l_=song.getNimi(),_r_="The Paradox.*"; if ( !_l_.matches(_r_) ) fail("From: Biisi line: 324" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}